version: v1
services:
  - type: web
    name: smart-health-assistant
    env: python
    repo: 230101120203-ops/Smart-Health-Assistant-
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
    disk:
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
